package com.goodworkalan.infuse;

import java.util.Locale;
import java.util.ResourceBundle;

/**
 * An exception for errors generated by the infusion package.
 *
 * @author Alan Gutierrez
 */
public class InfusionException extends RuntimeException {
    /** Serial version id. */
    private static final long serialVersionUID = -1L;
    
    /** The message context class. */
    public final Class<?> contextClass;
    
    /** The message error code. */
    public final String code;

    /**
     * Create an infusion exception with the given context, the given message
     * key, the given cause and the given positioned format arguments.
     * 
     * @param contextClass
     *            The error context.
     * @param messageKey
     *            The error message key.
     * @param arguments
     *            The positioned format arguments.
     */
    public InfusionException(Class<?> contextClass, String messageKey, Object... arguments) {
        this(null, contextClass, messageKey, arguments);
    }

    /**
     * Create an infusion exception with the given code and the given positioned
     * format arguments.
     * 
     * @param contextClass
     *            The error context.
     * @param code
     *            The error message code.
     * @param cause
     *            The cause.
     * @param arguments
     *            The positioned format arguments.
     */
    public InfusionException(Throwable cause, Class<?> contextClass, String code, Object...arguments) {
        super(formatMessage(contextClass, code, arguments), cause);
        this.contextClass = contextClass;
        this.code = code;
    }

    /**
     * Format the exception message using the message arguments to format the
     * message found with the message key in the message bundle found in the
     * package of the given context class.
     * 
     * @param contextClass
     *            The context class.
     * @param code
     *            The error code.
     * @param arguments
     *            The format message arguments.
     * @return The formatted message.
     */
    private final static String formatMessage(Class<?> contextClass, String code, Object...arguments) {
        String baseName = contextClass.getPackage().getName() + ".exceptions";
        String messageKey = contextClass.getSimpleName() + "/" + code;
        try {
            ResourceBundle bundle = ResourceBundle.getBundle(baseName, Locale.getDefault(), Thread.currentThread().getContextClassLoader());
            return String.format((String) bundle.getObject(messageKey), arguments);
        } catch (Exception e) {
            return String.format("Cannot load message key [%s] from bundle [%s] becuase [%s].", messageKey, baseName, e.getMessage());
        }
    }
    
    /**
     * Assert that the given exception is a reflection related
     * <code>Exception</code>. (FIXME Outgoing!)
     * 
     * @param e
     *            The throwable.
     * @return The throwable.
     * @exception RuntimeException
     *                if the throwable is an <code>RuntimeException</code> but
     *                not an <code>IllegalArgumentException</code>.
     * @exception Error
     *                if the throwable is an <code>Error</code> but not an
     *                <code>ExceptionInInitializerError</code>.
     */
    public static Throwable $(Throwable e) {
        if (e instanceof Error) { 
            if (!(e instanceof ExceptionInInitializerError)) {
                throw (Error) e;
            }
        } else if (e instanceof RuntimeException) {
            if (!(e instanceof SecurityException) && !(e instanceof IllegalArgumentException)) {
                throw (RuntimeException) e;
            }
        }
        return e;
    }
}
